@echo off

    echo URLs for the latest Canary ^(R0^) build of Microsoft Teams:
    node "src\v2.0\Ring 0\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 0\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 0\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 0\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 0\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 0\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 0\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 0\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 0\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 0\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 0\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest Teams ^(R1^) build of Microsoft Teams:
    node "src\v2.0\Ring 1\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 1\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 1\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 1\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 1\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 1\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 1\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 1\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 1\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 1\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest IT Admins Preview ^(R1.5 or BETA^) build of Microsoft Teams:
    node "src\v2.0\Ring 1.5\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 1.5\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 1.5\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 1.5\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 1.5\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 1.5\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 1.5\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 1.5\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 1.5\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 1.5\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.5\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest Developers Partners Preview ^(R1.6 or DP^) build of Microsoft Teams:
    node "src\v2.0\Ring 1.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 1.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 1.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 1.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 1.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 1.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 1.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 1.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 1.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 1.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 1.6\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest Microsoft Dogfood ^(R2 or DF^) build of Microsoft Teams:
    node "src\v2.0\Ring 2\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 2\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 2\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 2\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 2\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 2\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 2\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 2\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 2\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 2\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 2\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest TAP/Beta Users ^(R3 or TAP^) build of Microsoft Teams:
    node "src\v2.0\Ring 3\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 3\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 3\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 3\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 3\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 3\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 3\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 3\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 3\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 3\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest Public Developer Preview ^(R3.6 or P^) build of Microsoft Teams:
    node "src\v2.0\Ring 3.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 3.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 3.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 3.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 3.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 3.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 3.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 3.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 3.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 3.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.6\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest Microsoft Outer Ring ^(R3.9 or MS^) build of Microsoft Teams:
    node "src\v2.0\Ring 3.9\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 3.9\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 3.9\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 3.9\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 3.9\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 3.9\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 3.9\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 3.9\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 3.9\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 3.9\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 3.9\msix\win-arm64.js" | find "published"
    echo:
    echo:
    echo URLs for the latest Public ^(R4^) build of Microsoft Teams:
    node "src\v2.0\Ring 4\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-x64.js" | find "published"
    node "src\v2.0\Ring 4\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-x64.js" | find "published"
    node "src\v2.0\Ring 4\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-x86.js" | find "published"
    node "src\v2.0\Ring 4\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-x86.js" | find "published"
    node "src\v2.0\Ring 4\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\exe\win-arm64.js" | find "published"
    node "src\v2.0\Ring 4\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msi\win-arm64.js" | find "published"
    node "src\v2.0\Ring 4\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\pkg\osx-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\pkg\osx-x64.js" | find "published"
    node "src\v2.0\Ring 4\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-x64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-x64.js" | find "published"
    node "src\v2.0\Ring 4\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-x86.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-x86.js" | find "published"
    node "src\v2.0\Ring 4\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-arm64.js" | find "published"
    if %ERRORLEVEL% EQU 1 node "src\v2.0\Ring 4\msix\win-arm64.js" | find "published"
