Write-Output "URLs for the latest production build of Microsoft Teams classic:"
& "..\..\src\v1.0\Production\exe\win-x64.ps1"
& "..\..\src\v1.0\Production\msi\win-x64.ps1"
& "..\..\src\v1.0\Production\exe\win-x86.ps1"
& "..\..\src\v1.0\Production\msi\win-x86.ps1"
& "..\..\src\v1.0\Production\exe\win-arm64.ps1"
& "..\..\src\v1.0\Production\msi\win-arm64.ps1"
& "..\..\src\v1.0\Production\pkg\osx-x64 + osx-arm64.ps1"
