Write-Output "URLs for the latest daily build of Microsoft Teams:"
& "..\..\src\v1.0\Daily\exe\win-x64.ps1"
& "..\..\src\v1.0\Daily\msi\win-x64.ps1"
& "..\..\src\v1.0\Daily\exe\win-x86.ps1"
& "..\..\src\v1.0\Daily\msi\win-x86.ps1"
& "..\..\src\v1.0\Daily\exe\win-arm64.ps1"
& "..\..\src\v1.0\Daily\msi\win-arm64.ps1"
& "..\..\src\v1.0\Daily\pkg\osx-x64 + osx-arm64.ps1"
Write-Output ""
Write-Output "URLs for the latest experimental build of Microsoft Teams:"
& "..\..\src\v1.0\Experimental\exe\win-x64.ps1"
& "..\..\src\v1.0\Experimental\msi\win-x64.ps1"
& "..\..\src\v1.0\Experimental\exe\win-x86.ps1"
& "..\..\src\v1.0\Experimental\msi\win-x86.ps1"
& "..\..\src\v1.0\Experimental\exe\win-arm64.ps1"
& "..\..\src\v1.0\Experimental\msi\win-arm64.ps1"
& "..\..\src\v1.0\Experimental\pkg\osx-x64 + osx-arm64.ps1"
Write-Output ""
Write-Output "URLs for the latest preview build of Microsoft Teams:"
& "..\..\src\v1.0\Preview\exe\win-x64.ps1"
& "..\..\src\v1.0\Preview\msi\win-x64.ps1"
& "..\..\src\v1.0\Preview\exe\win-x86.ps1"
& "..\..\src\v1.0\Preview\msi\win-x86.ps1"
& "..\..\src\v1.0\Preview\exe\win-arm64.ps1"
& "..\..\src\v1.0\Preview\msi\win-arm64.ps1"
& "..\..\src\v1.0\Preview\pkg\osx-x64 + osx-arm64.ps1"
Write-Output ""
Write-Output "URLs for the latest production build of Microsoft Teams:"
& "..\..\src\v1.0\Production\exe\win-x64.ps1"
& "..\..\src\v1.0\Production\msi\win-x64.ps1"
& "..\..\src\v1.0\Production\exe\win-x86.ps1"
& "..\..\src\v1.0\Production\msi\win-x86.ps1"
& "..\..\src\v1.0\Production\exe\win-arm64.ps1"
& "..\..\src\v1.0\Production\msi\win-arm64.ps1"
& "..\..\src\v1.0\Production\pkg\osx-x64 + osx-arm64.ps1"
