Write-Output "URLs for the latest preview build of Microsoft Teams:"
& "..\..\src\v1.0\Preview\exe\win-x64.ps1"
& "..\..\src\v1.0\Preview\msi\win-x64.ps1"
& "..\..\src\v1.0\Preview\exe\win-x86.ps1"
& "..\..\src\v1.0\Preview\msi\win-x86.ps1"
& "..\..\src\v1.0\Preview\exe\win-arm64.ps1"
& "..\..\src\v1.0\Preview\msi\win-arm64.ps1"
& "..\..\src\v1.0\Preview\pkg\osx-x64.ps1"
& "..\..\src\v1.0\Preview\deb\linux-x64.ps1"
& "..\..\src\v1.0\Preview\rpm\linux-x64.ps1"
Write-Output ""
Write-Output "URLs for the latest production build of Microsoft Teams:"
& "..\..\src\v1.0\Production\exe\win-x64.ps1"
& "..\..\src\v1.0\Production\msi\win-x64.ps1"
& "..\..\src\v1.0\Production\exe\win-x86.ps1"
& "..\..\src\v1.0\Production\msi\win-x86.ps1"
& "..\..\src\v1.0\Production\exe\win-arm64.ps1"
& "..\..\src\v1.0\Production\msi\win-arm64.ps1"
& "..\..\src\v1.0\Production\pkg\osx-x64.ps1"
& "..\..\src\v1.0\Production\deb\linux-x64.ps1"
& "..\..\src\v1.0\Production\rpm\linux-x64.ps1"
