Write-Output "URLs for the latest Canary (R0) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Canary Slimcore (R0s) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Teams (R1) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest IT Admins Preview (R1.5 or BETA) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Developers Partners Preview (R1.6 or DP) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Microsoft Dogfood (R2 or DF) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest TAP/Beta Users (R3 or TAP) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Early Access (R3.6 or EA) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Microsoft Outer Ring (R3.9 or MS) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Public (R4) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.0 — Microsoft Teams (free):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams Rooms on Windows:"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Public GCC (R4) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Public GCC High (R4) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Public DoD (R4) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output ""
Write-Output ""
Write-Output "URLs for the latest Public Gallatin (R4) build of Microsoft Teams:"
Write-Output ""
Write-Output "  Teams 1.0 — Microsoft Teams classic (work or school)"
& "..\src\Get-MicrosoftTeams.ps1"
Write-Output "  Teams 2.1 — Microsoft Teams (work or school):"
& "..\src\Get-MicrosoftTeams.ps1"
